baseURL = "https://froggy0-pro.github.io/mes-cours/"
languageCode = "fr-fr"
title = "Mes cours"
theme = "book"

enableGitInfo = true
relativeURLs = true
canonifyURLs = true


[params]
  BookSection = "docs"
  BookTheme = "light"
  BookToC = true
  BookSearch = true
  BookKaTeX = true