baseURL = "https://froggy0-pro.github.io/mes-cours/"
languageCode = "fr-fr"
title = "Mes cours"
theme = "book"

enableGitInfo = true
relativeURLs = false
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  BookTheme = "light"
  BookToC = true
  BookSearch = true
  BookKaTeX = true
  BookMenuBundle = "/docs"
  BookSection = "docs"
  BookMenuSort = "weight"
  BookCollapseSection = true
  BookMenuWidth = "20rem"
  BookBodyMaxWidth = "60rem"



